services:

    WordRepository:
        class:     WordSelector\Repository\WordRepository
        factory:   [ '@EntityManager', getRepository ]
        arguments: [ WordSelector\Entity\Word ]

    WordSelector:
        class:     WordSelector\DoctrineWordSelector
        arguments: [ '@WordRepository' ]